### ISSUE TITLE
bug: Double scrollbar in the user manual section.

### ISSUE THREAD

**Issue by alicangunduz** [acikyazilimagi/musahit-harita-frontend#10]
## Bug Definition
The instruction manual part is double scrollbars

**discord username: alicangunduz#0001**

## Bug environment
https://musahit-harita-frontend.vercel.app/

## Describe how you are producing the bug step by step

1. Go to https://musahit-harita-frontend.vercel.app/ 
2. Open the user manual.

## Expected Behaviour
Single scrollbar

## Screen shots
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/54004830/519e0ded-6f11-42d0-b7ea-578e067127c0)

**Comment by sevilayerkan** [comment]
Since user manual section had updated this bug will not occur now in the [stage](https://musahit-harita-frontend-git-stage-acikyazilim.vercel.app/). Because of that i'm closing the issue. 

If the error still persists, we can reopen the issue.
