### ISSUE TITLE
böğ: Sandık Konumu Bul düğmesinde açılan süzgeçte tuşlar işlemiyor

### ISSUE THREAD

**Issue by volkantash** [acikyazilimagi/musahit-harita-frontend#113]
## Böğ sonlamı
Seçim konumu bul düğmesine bastıktan sonra açılan süzgeçte il adı arar iken bir tuşa bastığımda bir il adına odaklanmıyor. Örneğin İstanbul ilini seçeceğim. İ tuşuna bastığımda süzgeç içinde odaklama işlemiyor.  

## Böğ çevresi

https://musahit-harita-frontend-git-stage-acikyazilim.vercel.app/

## Böğ durumunu adım adım anlatmak

1. https://musahit-harita-frontend-git-stage-acikyazilim.vercel.app/ anabetine giriniz.
2. "Sandık konumu bul" adlı düğmeye tıklayınız.
2. Açılan süzgeçte "Şehir" yazan seçeğe tıklayınız.
3. "İstanbul" ilini hızlıca seçmek için "İ" tuşuna basınız.
4. İşlemediğini görebilirsiniz.

## Umulan İşleyiş
"İ" tuşuna basınca "İ" harfi ile başlayan illere erebilmek.

## Masaüstü Bilgileri
- İşletim düzeni: Windows 10
- Tarayıcı: Firefox 
- Sürüm: 113.*

**Comment by usirin** [comment]
@ssibrahimbas bunu yapmakla su an ugrasmayabiliriz abi.

nasil bir sey planliyosun?

**Comment by salihdev0** [comment]
Select yerine autocomplete kullandım çok zaman kaybetmeden yaptım #128'de.

**Comment by usirin** [comment]
PR'da da yazdim buraya da ekleyeyim:

> Abi ellerine saglik fakat son dakika bu kadar kompleks bi degisikligi almayalim iceri. iki scroll ederek cozulecek bi olay icin bu kadar kod yazmaya degmez. kusura bakma aldigini gorseydim, baslamadan uyarirdim.
