### ISSUE TITLE
refactor: User guide language confusion

### ISSUE THREAD

**Issue by sevilayerkan** [acikyazilimagi/musahit-harita-frontend#115]
## Bug Definition
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/22706692/538d5036-9b4a-497f-a105-494e193fd746)
It was reported that different wording is used for the same term in marked places in the user guide. I think this might confuse someone who is using the site for the first time, so it might be better to choose a single Turkish expression for the pins.

-- Please add discord contact information
** discord username: @notdepressedeveloper **

**Comment by sevilayerkan** [comment]
As for the term "okullar", in cities the polling stations are in schools, but in villages and rural areas they can also be in village cafes and muhtar offices, and we may consider changing this to avoid confusion.

**Comment by salihdev0** [comment]
In #126, I wrote the new text in English and Turkish. Can you check for new texts @sevilayerkan?
