### ISSUE TITLE
bug: User manual content should be updated

### ISSUE THREAD

**Issue by sevilayerkan** [acikyazilimagi/musahit-harita-frontend#13]
## Bug Definition
The user manual content from the old project should be updated.

![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/22706692/ddb6f08f-0a38-40ae-ad22-8dcf953fb65c)

** discord username: @notDepresseDeveloper#0919**

## Bug environment
https://musahit-harita-frontend.vercel.app/

## Describe how you are producing the bug step by step

1. Go to (https://musahit-harita-frontend.vercel.app/)
2. Click ? icon to open manual 
3. Bug appears

**Comment by eraygundogmus** [comment]
this task is done by @ssibrahimbas
