### ISSUE TITLE
WIP: Change "Volunteer" Button as "Upload Record"

### ISSUE THREAD

**Issue by mehmetalicakir** [acikyazilimagi/musahit-harita-frontend#131]
**When finalized "WIP" will be removed**
Change button text as "Upload Record" for English and "Tutanak Yükle" for Turkish

<img width="271" alt="image" src="https://github.com/acikkaynak/musahit-harita-frontend/assets/32022785/267f52c4-faf9-4494-92e5-d9b0f9385218">

<img width="201" alt="image" src="https://github.com/acikkaynak/musahit-harita-frontend/assets/32022785/4f628463-e130-43d9-beeb-9d8e486694a4">

**Comment by usirin** [comment]
We are not gonna do this. I am opening a task to remove the "Volunteer" button.
