### ISSUE TITLE
bug: Bring it back in case the location is accidentally lost

### ISSUE THREAD

**Issue by alicangunduz** [acikyazilimagi/musahit-harita-frontend#14]
## Bug Definition
If there is a selected position and it is moved away from the position, it should come back to the position by selecting it again, but this function does not work correctly.

-- Please add discord contact information
** discord username: alicangunduz#0001 **

## Bug environment
https://musahit-harita-frontend.vercel.app/

## Describe how you are producing the bug step by step

1. Go to https://musahit-harita-frontend.vercel.app/
2. Click "Okul Sorgula"
3. Choose any city
4. Then drag the map with the mouse to move it to another location
5. Select your first province from the "Okul Sorgula" field again

## Expected Behaviour
It should come back when you select the lost position again.

## Screen shots
[screen-capture.webm](https://github.com/acikkaynak/musahit-harita-frontend/assets/54004830/15265e1e-caf5-459b-b920-4c896e121a9c)

**Comment by sevilayerkan** [comment]
Since `Apply Options` button had added this bug will not occur now in the [stage](https://musahit-harita-frontend-git-stage-acikyazilim.vercel.app/). Because of that i'm closing the issue. 

If the error still persists, we can reopen the issue.
