### ISSUE TITLE
bug: Documents in the bottom can be updated

### ISSUE THREAD

**Issue by sevilayerkan** [acikyazilimagi/musahit-harita-frontend#15]
## Bug Definition
The cookie, privacy documents at the bottom of the site can be updated. There are still Afetharita documents in the links there.

** discord username: @notDepresseDeveloper#0919**

## Bug environment
https://musahit-harita-frontend.vercel.app/

## Describe how you are producing the bug step by step

1. Go to bottom of the page
2. Click `Cookies` or `Privacy` buttons
3. Check the documents in the link
4. Bug appears

**Comment by sevilayerkan** [comment]
In addition to this issue `Data sources` content also needs to be updated.

![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/22706692/02b27a4d-0840-406b-af5a-96976b7d18a1)

**Comment by kingofsevens** [comment]
Let's remove it completely. Only thing we need is KVKK. (GDPR) text at the moment.

**Comment by usirin** [comment]
I've deleted the data source text & text with #64 but need your input for the cookies and privacy ones @kingofsevens

**Comment by Batuhandgenc** [comment]
Cookies Text Update.

[Here](https://docs.google.com/document/d/1PsQIlJUei89j4q2RUPhOk3AufZay4EJIbNcUodaGv8I/edit?usp=sharing) 


Can we remove the Privacy button? Because we don't need to collect any data.
