### ISSUE TITLE
bug: neighborhood and school content in the query field is not available

### ISSUE THREAD

**Issue by alicangunduz** [acikyazilimagi/musahit-harita-frontend#16]
## Bug Definition
neighborhood and school content in the query field is not available

**discord username: alicangunduz#0001**

## Bug environment
https://musahit-harita-frontend.vercel.app/

## Describe how you are producing the bug step by step

1. Go to https://musahit-harita-frontend.vercel.app/
2. Click "Okul Sorgula"
3. Select province and district
4. No neighborhoods and no schools
5. Bug appears

## Expected Behaviour
Visibility of neighborhoods and schools

## Screen shots
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/54004830/a6ff35d3-9113-4b07-9360-1ae459611f40)

**Comment by usirin** [comment]
Gonna be fixed with #29
