### ISSUE TITLE
bug: 404 Page Return Button Does Not Work

### ISSUE THREAD

**Issue by akselsaatci** [acikyazilimagi/musahit-harita-frontend#165]
## Bug Definition
In 404 error page return to home button doesn't return to home page instead it returns to 404 page.

-- Please add discord contact information
** discord username: @Aksel#7033 **

## Bug environment
Describe the environment produces the bug. For example:
https://secim.gonullu.io/en/
## Describe how you are producing the bug step by step

1. Go to https://secim.gonullu.io/en/asdasd
2. Click the return to home button

## Expected Behaviour
The button should return user to home page.

## Desktop Information
- Windows 11
- Mozilla Fİrefox, Safari

## Mobile Phone Information
- Devıce: [for example iPhone6]
- Operating System (with the version): [for example iOS8.1]
- Version [for example default browser, safari]
- Browser Version [for example 22]

**Comment by aksel** [comment]
I was very confused for a moment there haha 😅

**Comment by akselsaatci** [comment]
> I was very confused for a moment there haha 😅

sorry for misunderstanding i was trying to write my discord username 😅 it was my bad sorry
