### ISSUE TITLE
bug: When the language selection field is open, double-clicking is required to open the other fields.

### ISSUE THREAD

**Issue by alicangunduz** [acikyazilimagi/musahit-harita-frontend#17]
## Bug Definition
When the language selection field is open, double-clicking is required to open the other fields.

**discord username: alicangunduz#0001**

## Bug environment
https://musahit-harita-frontend.vercel.app/

## Describe how you are producing the bug step by step

1. Go to https://musahit-harita-frontend.vercel.app/
2. Open the language selection area
3. Try to open the school search
4. Bug appears

## Expected Behaviour
Even if a field is to close, it should close on the 1st click. 2nd click should not be needed

## Screen shots
[screen-capture.webm](https://github.com/acikkaynak/musahit-harita-frontend/assets/54004830/cfd7d15f-6e61-4722-808e-dcb052affd75)

**Comment by oguzergul** [comment]
The select component focuses on the first option as the default behavior. I don't think this is a critical bug. Language selection is a one-time job. cc: @usirin

**Comment by usirin** [comment]
This is a default behavior of a regular dropdown/select components, so it makes sense that the first click outside of dropdown actually closes it.

There is nothing to be fixed here so closing it. ty @alicangunduz
