### ISSUE TITLE
bug: Cookie and confidentiality agreement content should be regulated

### ISSUE THREAD

**Issue by alicangunduz** [acikyazilimagi/musahit-harita-frontend#19]
## Bug Definition
Cookie and confidentiality agreement content should be regulated

**discord username: alicangunduz#0001**

## Bug environment
https://musahit-harita-frontend.vercel.app/cerez.pdf
https://musahit-harita-frontend.vercel.app/gizlilik.pdf

## Describe how you are producing the bug step by step

1. Go to https://musahit-harita-frontend.vercel.app/gizlilik.pdf   ,  https://musahit-harita-frontend.vercel.app/cerez.pdf
2. Read this
3. Bug appears

## Expected Behaviour
afetharita should be replaced and new articles should be added if necessary.

## Screen shots
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/54004830/286cdf81-c1b5-4f95-b0b1-2514bd54ab1f)
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/54004830/3b8cf00e-32a7-42f9-92bb-82161da64c56)

**Comment by sevilayerkan** [comment]
This issue is duplicated with #15

**Comment by oguzergul** [comment]
@alicangunduz, @sevilayerkan is right. we can continue with #15 ❤️
