### ISSUE TITLE
feat: Update About Us and other page content

### ISSUE THREAD

**Issue by bltMustafa** [acikyazilimagi/musahit-harita-frontend#24]
** discord username: `@Mustafa Bolat #4560` **

**Comment by eraygundogmus** [comment]
@bltMustafa content alabilir miyiz bu issue altında?

**Comment by bltMustafa** [comment]
@eraygundogmus abi design ekibi ile görüştüm content hazır olunca atacağım .

**Comment by Batuhandgenc** [comment]
Sadece bir kısmını oluşturduk akşam issueslar rahat açılabilsin diye. Bugün geriye kalan kısımları halledeceğiz @ipekderin  ile. 
fyi @eraygundogmus @bltMustafa

**Comment by salihdev0** [comment]
bana atayabilirsiniz şu anda üzerinde çalışıyorum
