### ISSUE TITLE
feat:  Page: Ana Sayfa & Alan Tarandı

### ISSUE THREAD

**Issue by bltMustafa** [acikyazilimagi/musahit-harita-frontend#25]
![Ana Sayfa _1](https://github.com/acikkaynak/musahit-harita-frontend/assets/92399033/b3c4025a-bee5-4aa6-84be-7b47a748438e) 
![Ana Sayfa_2](https://github.com/acikkaynak/musahit-harita-frontend/assets/92399033/d574b7b3-a358-4dbf-95f8-00cfeee91245)

** discord username: `@Mustafa Bolat #4560 `**

**Comment by eraygundogmus** [comment]
bu yapıldı sanırım zaten, ayrıca gerek de kalmayabilir artık bu feature'a, sabit pinler olacağı için, o yüzden şimdilik kapatıyorum. discorddan konuşalım

https://discord.com/channels/1072074800622739476/1108716857759891497
