### ISSUE TITLE
feat: Page: Pin Detay

### ISSUE THREAD

**Issue by bltMustafa** [acikyazilimagi/musahit-harita-frontend#27]
On Click of pinned neighbourhoud display modal

Implement Social Share button
Implement "Gönüllü Ol" button - opens a form

The drawer info will be finalized - TBC

![pindetay](https://github.com/acikkaynak/musahit-harita-frontend/assets/92399033/748177cf-d224-4692-b4db-81eaec6f4501)

** discord username: `@Mustafa Bolat#4560 `**

**Comment by usirin** [comment]
Duplicate of #38
