### ISSUE TITLE
bug: Zoom data is not properly transmitted with url

### ISSUE THREAD

**Issue by sevilayerkan** [acikyazilimagi/musahit-harita-frontend#33]
## Bug Definition
Zoom data is not properly transmitted with url. Zoom data is not displayed in the same way when the link is opened in another window/tab. Ideally, when a link is shared, the desired location should be displayed in the same way as the person sharing it.

For example:
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/22706692/9a067797-6284-42ba-90fe-ed00c7159713)

When we open the link in the top picture in a different place, it looks like the following:
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/22706692/695c2328-a6c6-4331-88db-3f6e71f25daf)

-- Please add discord contact information
** discord username: notDepresseDeveloper#0919

## Bug environment
https://musahit-harita-frontend-git-pins-on-map-acikyazilim.vercel.app/

**Comment by sevilayerkan** [comment]
As reports from users this issue is still persisting.

User report: 
`After selecting one of the crate points and saying share the link, when I open the link it gives, only the drawer part opens, it does not open zoomed in the map.`

**Comment by usirin** [comment]
Cannot reproduce.
