### ISSUE TITLE
bug: Map inaccuracy: Focus geolocation causing misplacement 

### ISSUE THREAD

**Issue by Batuhandgenc** [acikyazilimagi/musahit-harita-frontend#45]
## Issue Description
I have encountered an issue with the map feature where the location is inaccurately pinpointed. When I find a place on the map and select "Show on Maps," it places me approximately 20-30km away from the intended location

** discord username: Batu#8448**

## Steps to Reproduce:
1. Filter Map Location
2. Search for a specific location.
3. Notice that the displayed location is approximately 20km off from the intended spot.

## Expected Behavior:

When I a chosen location, the map should accurately display the exact location I selected.

## Actual Behavior:

The map is placing the location approximately 20km away from the intended spot, leading to incorrect geolocation.

## Additional Information:

![image](https://github.com/acikkaynak/musahit-harita-backend/assets/105302702/7fea6a95-d2e9-4117-ba74-298eb147d5ed)
![image](https://github.com/acikkaynak/musahit-harita-backend/assets/105302702/ef2dced5-27fc-4213-8eab-37096b6cf489)
![image](https://github.com/acikkaynak/musahit-harita-backend/assets/105302702/865ac6b1-9e67-497f-abf6-f958cf2b72d1)

## Expected Screenshots:
![image](https://github.com/acikkaynak/musahit-harita-backend/assets/105302702/82b8009a-e5e5-4783-85f6-4f96473db9f0)

**Comment by usirin** [comment]
This is mainly due to the coordinates calculation we did for neighborhoods to show this data:

- we had data with bounding boxes,
- we calculated some middle point to it
- and we used that point to show the neighborhood

as long as we don't have specific coordinates for each neighborhood, dunno how we can fix this.

cc @kingofsevens

**Comment by siniradam** [comment]
This data set swapped with new one.
