### ISSUE TITLE
feat: update SEO content changes due to new project

### ISSUE THREAD

**Issue by eraygundogmus** [acikyazilimagi/musahit-harita-frontend#51]
Since we are using the afetharita.com repository's clone, the SEO content kept same with old one. 

We need to update that.

**Comment by usirin** [comment]
@eraygundogmus We fixed some of the seo issues with #41 i think what we are missing is embed image, what else do you know we are missing?

**Comment by eraygundogmus** [comment]
did not see that closed issue, sorry! we can close that after embed image @usirin

**Comment by usirin** [comment]
@eraygundogmus no worries, just wanted to make sure if we missed a place or not. TY so much for the report <3

**Comment by Batuhandgenc** [comment]
I forwarded the up-to-date logo files to @usirin . We also discussed that we would use different variations if necessary.
