### ISSUE TITLE
feat:  KVKK Text Editing Request.

### ISSUE THREAD

**Issue by Batuhandgenc** [acikyazilimagi/musahit-harita-frontend#57]
## Request
In light of the recent updates, there is a possibility that we may require the dataset, and therefore, we are obliged to have the KVKK text.

** discord username: Batu#8448 **

## Alternatives
We have received an up-to-date KVKK text. It needs to be reviewed and discussed through the channel.

**Comment by Batuhandgenc** [comment]
@kingofsevens

**Comment by usirin** [comment]
Closing this for now as we don't collect any data yet. we have the document ready if we ever need to put it on the site.
