### ISSUE TITLE
bug: Map starts at the wrong place

### ISSUE THREAD

**Issue by sevilayerkan** [acikyazilimagi/musahit-harita-frontend#60]
## Bug Definition
Map starts at the wrong place. When the map is opened for the first time it should be seen focused to `Ankara` right but right now it seens as in the ss
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/22706692/94a52005-2836-4703-a734-29c29f0e21a0)

-- Please add discord contact information
** discord username: @notdepressedeveloper **

## Bug environment
Describe the environment produces the bug. For example:
https://musahit-harita-frontend-git-stage-acikyazilim.vercel.app

**Comment by usirin** [comment]
@sevilayerkan i cannot reproduce this, i think this is related to #59

**Comment by usirin** [comment]
This is fixed #85
