### ISSUE TITLE
bug: Heat maps are not properly visible after a certain zoom level

### ISSUE THREAD

**Issue by sevilayerkan** [acikyazilimagi/musahit-harita-frontend#61]
## Bug Definition
Heat maps are not properly visible after a certain zoom level

-- Please add discord contact information
** discord username: @notdepressedeveloper **

## Bug environment
Describe the environment produces the bug. For example:
https://musahit-harita-frontend-git-stage-acikyazilim.vercel.app

## Describe how you are producing the bug step by step

1. Find one of the high density
2. Zoom in to that area
3. Observe the heat maps in the area
4. Bug appears

## Expected Behaviour
Heatmaps should be visible in any zoom level

## Screen shots
- For the area that pinned 2338
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/22706692/178b4347-2714-4317-b5cf-8ad14b4b55b3)
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/22706692/17106846-571e-472f-b5fd-05bd77b82774)

**Comment by usirin** [comment]
Let's close this, i will address it after we have everything merged.
