### ISSUE TITLE
feat:  The usage of CartoDB enables a more convenient and effective utilization and display of pins.

### ISSUE THREAD

**Issue by bltMustafa** [acikyazilimagi/musahit-harita-frontend#63]
https://leaflet-extras.github.io/leaflet-providers/preview/

![IMG-20230525-WA0000](https://github.com/acikkaynak/musahit-harita-frontend/assets/92399033/2315c56c-0aa6-4490-bdf1-f0ab7633af16)

** discord username: `@Mustafa Bolat#4560 `**

**Comment by usirin** [comment]
We need this as this makes it clearer to see pins on the map.
