### ISSUE TITLE
update : dialog box added

### ISSUE THREAD

**Issue by Batuhandgenc** [acikyazilimagi/musahit-harita-frontend#70]
Upon deemed necessary, "dialog box" and "Veriler Oy ve Ötesi Tarafından Sağlanmaktadır" have been added to the Figma. The new design is as follows.
The link we will redirect to : oyveotesi.org/kayit
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/105302702/a855508d-e658-4170-87e5-805f5d99888c)
![image](https://github.com/acikkaynak/musahit-harita-frontend/assets/105302702/1e7d999f-18b6-4f8e-8a74-feb83e42ad19)

**Comment by salihdev0** [comment]
I'm working on it

**Comment by kingofsevens** [comment]
@ssibrahimbas link should open new tab to https://oyveotesi.org/kayit/ 
I guess that is because of the env value...
