### ISSUE TITLE
bug: site title still says "Afet haritası"

### ISSUE THREAD

**Issue by usirin** [acikyazilimagi/musahit-harita-frontend#8]
## Bug Definition
Site title says "Afet haritası" we need to update it to "secim.gonullu.io"

discord username: `umut#3072`

**Comment by sevilayerkan** [comment]
In addition to this issue we also need to update site icon too.

**Comment by Batuhandgenc** [comment]
Our proposed names on the agenda and Umut's suggestions actually make sense. Homwever, due to certain reasons we are unable to progress rapidly. Once the name is finalized we weill complate the visual work for the logo with @ipekderin

discord username : Batu#8448

**Comment by alicangunduz** [comment]
Meta tag fields need to be filled in with similar names and keywords
