### ISSUE TITLE
bug: drawer data intensity level colors are wrong

### ISSUE THREAD

**Issue by usirin** [acikyazilimagi/musahit-harita-frontend#81]
Everything returns "Orta" and it's always "red"

investigate if this is from backend

**Comment by sertunc** [comment]
and when closing the drawer, changing the "İhtiyaç" tag color and desc.


https://github.com/acikkaynak/musahit-harita-frontend/assets/6024003/398f5a69-223c-437e-871e-06cb7e881bb0

**Comment by sevilayerkan** [comment]
@sertunc Thanks for reporting ❤️  I opened new issue related to this bug we can continue from there #90
