### ISSUE TITLE
refactor: Updating the favicon logo.svg

### ISSUE THREAD

**Issue by yavuzKomecoglu** [acikyazilimagi/musahit-harita-frontend#91]
### Refactor Request

-- fill in the line below:
** YavuzKomecoglu#9240 **

Is your refactor request pertaining to a problem? Please elaborate.

**updating favicon with new logo
URL: https://secim.gonullu.io/logo.svg**

### Suggested solution

Updating logo.svg with one of the newly designed volunteer logos

**Comment by usirin** [comment]
Closed with #96
